server:
  port: 8069

spring:
  application:
    name: daily-read
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/daily_read
    username: postgres
    password: 'fghvvcfdutynn'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    config:
      allow-override: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: bigmitchsystems@gmail.com
    password: 'vylwczjezjgyrpok'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    default-encoding: UTF-8
  main:
    allow-bean-definition-overriding: true

daily-read:
  random-verse: https://quotes.rest/bible/verse.json
  daily-verse: https://quotes.rest/bible/vod.json

